update to flutter 3.22.0
JonasWanke/swipeable_page_route pull request #51
Opened 2024-05-15 10:17 UTC by nimr77

this just a change on the transactions to use 
```      route.navigator!.userGestureInProgress ```

since after updating for 3.22.0 there was a removed function:
```CupertinoRouteTransitionMixin.isPopGestureInProgress(route)```

2024-05-15 22:57 UTC, axsann commented
It should simply be replaced with `route.popGestureInProgress`.

2024-05-16 13:33 UTC, JonasWanke requested changes
Thanks for creating this PR! The content changes look good, but can you please revert the reorderings inside `page_route.dart`?

2024-05-21 15:31 UTC, JonasWanke commented
I went ahead and merged #54 to support Flutter 3.22, though I can still merge the iOS changes from this PR if you want

2024-05-21 15:56 UTC, nimr77 commented
> I went ahead and merged #54 to support Flutter 3.22, though I can still merge the iOS changes from this PR if you want

Ok perfect Go ahead and merge it, Thanks

2024-05-22 07:00 UTC, JonasWanke commented
Can you please undo the formatting changes in `page_route.dart` and resolve the merge conflicts?

2024-12-16 12:08 UTC, closed without merging